# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: "typings/.*"

repos:
    - repo: local
      hooks:
          - id: pyright
            name: pyright
            entry: pyright
            language: node
            pass_filenames: false
            types: [python]
            additional_dependencies: ["pyright@1.1.374"]

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.5.6
      hooks:
        - id: ruff
          args: [ --fix ]

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
          - id: trailing-whitespace
          - id: check-yaml
          - id: check-added-large-files
