on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "**"
env:
  containerRegistry: spinshot.azurecr.io
  imageRepository: cyberbattle
  tag: ${{ github.sha }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - run: |
          docker build . -t  ${{ env.containerRegistry }}/${{ env.imageRepository }}:${{ env.tag }}

      - name: Login to ACR
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ env.containerRegistry }}
          username: ${{ secrets.ACR_TOKEN_NAME }}
          password: ${{ secrets.ACR_TOKEN_PASSWORD }}
        if: github.ref_name == 'main'

      - run: |
          docker push ${{ env.containerRegistry }}/${{ env.imageRepository }}:${{ env.tag }}
        if: github.ref_name == 'main'
