on:
  push:
    branches:
      - main
env:
  containerRegistry: spinshot.azurecr.io
  imageRepository: cyberbattle
  tag: ${{ github.sha }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.containerRegistry }}
          username: ${{ secrets.ACR_TOKEN_NAME }}
          password: ${{ secrets.ACR_TOKEN_PASSWORD }}

      - run: |
          docker build . -t  ${{ env.containerRegistry }}/${{ env.imageRepository }}:${{ env.tag }}
          docker push ${{ env.containerRegistry }}/${{ env.imageRepository }}:${{ env.tag }}
